#!/bin/bash

VOLUME=`cat | tail -n2 | awk '{ print $5 }' | tr '\n' ' '`

LEFT=`echo $VOLUME | awk '{ print $1 }' | sed -r 's/^[^0-9]*([0-9]+).*/\1/'`
RIGHT=`echo $VOLUME | awk '{ print $2 }' | sed -r 's/^[^0-9]*([0-9]+).*/\1/'`

echo "{\"left\": $LEFT, \"right\": $RIGHT}"
