#!/bin/bash
cd `dirname $0`

DEVICE_IN=UA25
DEVICE_OUT=IQaudIODAC

REC="arecord -f cd -D plughw:$DEVICE_IN"
PLAY="aplay -f cd -D plughw:$DEVICE_OUT"

$REC 2>>.log </dev/null | $PLAY 2>>.log >>.log &

echo `jobs -p` >.pidfile

./status
