#!/bin/bash
cd `dirname $0`

USERNAME=whoiby
PASSWORD=`cat /home/pi/.pass`
NAME=PiNette

for DEV in $(find /dev/snd -type c); do
  DEVICE_ARGS="$DEVICE_ARGS --device=$DEV:$DEV"
done

docker run -d -p 4000:4000 -cidfile=./.cidfile $DEVICE_ARGS spotify-connect-web --username $USERNAME --password $PASSWORD --name $NAME  &>>./.log 2>/dev/null

./status
